-- 1. 创建用户表
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 创建待办事项表
CREATE TABLE IF NOT EXISTS todos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1. 创建管理员表
CREATE TABLE IF NOT EXISTS heal_admin (
    -- 主键：使用 IDENTITY 语法，这是现代 PostgreSQL 推荐的自增写法
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 用户名：必填，建议设置唯一约束防止重名
    username VARCHAR(50) NOT NULL UNIQUE,

    -- 邮箱：可选，但在重置密码或通知时很有用
    email VARCHAR(255),

    -- 密码哈希：**重要**，永远不要存明文密码，这里预留 255 长度以适配 bcrypt/argon2 等算法
    password_hash VARCHAR(255) NOT NULL,

    -- 角色：方便后续扩展权限（如 'super_admin', 'editor'）
    role VARCHAR(20) NOT NULL DEFAULT 'admin',

    -- 时间戳：使用 TIMESTAMPTZ 自动处理时区问题
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE heal_menus (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    path VARCHAR(100) NOT NULL,
    title VARCHAR(50) NOT NULL,
    icon VARCHAR(50),
    
    -- 核心字段：控制谁能看到
    role VARCHAR(20) NOT NULL DEFAULT 'admin',

    -- 排序
    sort INT NOT NULL DEFAULT 0
);

INSERT INTO heal_menus (name, path, title, icon, role, sort) VALUES
('home', '/home', '首页', 'Home', 'admin', 1),
('dashboard', '/dashboard', '控制台', 'Dashboard', 'admin', 2),
('admin', '/admin', '管理员管理', 'UserCog', 'admin', 3),
('article', '/article', '内容管理', 'FileText', 'admin', 4),
('user', '/user', '用户管理', 'Users', 'admin', 5);

CREATE TABLE heal_article (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    author_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

--- 下面是自动更新 updated_at 的“魔法”代码 ---
/* 
-- 3. 创建一个通用的函数，用来自动更新时间
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- 4. 给 users 表绑定这个自动更新功能
CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON users 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 5. 给 todos 表绑定这个自动更新功能
CREATE TRIGGER update_todos_updated_at 
    BEFORE UPDATE ON todos 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
    */