-- 1. 创建用户表
CREATE TABLE IF NOT EXISTS heal_users (
    -- 主键：使用 IDENTITY 语法，这是现代 PostgreSQL 推荐的自增写法
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 用户名：必填，建议设置唯一约束防止重名
    username VARCHAR(50) NOT NULL UNIQUE,

    -- 邮箱：可选，但在重置密码或通知时很有用
    email VARCHAR(255),

    -- 密码哈希：**重要**，永远不要存明文密码，这里预留 255 长度以适配 bcrypt/argon2 等算法
    password_hash VARCHAR(255) NOT NULL,

    -- 角色：方便后续扩展权限（如 'super_admin', 'editor'）
    role VARCHAR(20) NOT NULL DEFAULT 'admin',

    -- 时间戳：使用 TIMESTAMPTZ 自动处理时区问题
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
--密码: 123123
INSERT INTO heal_users (username,email,password_hash,role) VALUES 
('admin','admin@admin.com','$2b$12$Jqe0CHNXvKlWIqbm6WUht.wgTuYwhHFkB0YPJhcQGYoreDqdlv312','admin');

-- 2. 创建待办事项表
CREATE TABLE IF NOT EXISTS todos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);




CREATE TABLE IF NOT EXISTS heal_menus (
    id SERIAL PRIMARY KEY,

    name VARCHAR(50) NOT NULL,      -- 路由名
    path VARCHAR(100) NOT NULL,     -- 路由路径
    title VARCHAR(50) NOT NULL,     -- 显示名称
    icon VARCHAR(50),               -- 图标

    role VARCHAR(20) NOT NULL DEFAULT 'admin', -- 哪个角色可见（你现在简化版核心）

    parent_id INT DEFAULT NULL,     -- 支持树结构（可选但建议留）
    sort INT DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO heal_menus (name, path, title, icon, role, sort) VALUES
('dashboard', '/dashboard', '控制台', 'Dome', 'admin', 1),
('admin', '/admin', '管理员管理', 'UserCog', 'admin', 2),
('article', '/article', '内容管理', 'FileText', 'admin', 3),
('user', '/user', '用户管理', 'Users', 'admin', 4),
('menu', '/menu', '菜单管理', 'Menu', 'admin', 5);

CREATE TABLE heal_article (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    author_id INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);





--- 下面是自动更新 updated_at 的“魔法”代码 ---

创建一个通用的函数，用来自动更新时间
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';


CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON heal_users 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON heal_menus 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_todos_updated_at 
    BEFORE UPDATE ON heal_article 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
    